### PR TITLE
Move ifelse condition checking to pre-codegen checks

### LINKED ISSUE #90: Parameter not allowed in ifelse
I think this model should work:
```
hadiff' ~ normal(skill[hteam, hnumber] - skill[ateam, anumber], sigma);
skill[team, gnumber]' = (
    skill[team, shift(gnumber, 1)] +
    epsilon[team, gnumber] * ifelse(gnumber == 0, tau0, tau)
);
epsilon[team, gnumber] ~ normal(0.0, 1.0);
tau<lower=0.0> ~ exponential(1.0);
tau0<lower=0.0> ~ exponential(10.0);
sigma<lower=0.0> ~ exponential(1.0);
```

Example data:
```
date,hteam,ateam,hscore,ascore,hadiff,hnumber,anumber
2019-10-22,TOR,NOP,130.0,122.0,8.0,0,0
2019-10-22,LAC,LAL,112.0,102.0,10.0,0,0
2019-10-23,CHA,CHI,126.0,125.0,1.0,0,0
2019-10-23,IND,DET,110.0,119.0,-9.0,0,0
2019-10-23,ORL,CLE,94.0,85.0,9.0,0,0
2019-10-23,BKN,MIN,126.0,127.0,-1.0,0,0
```

Error message:
```
rat.exceptions.ParseError: An error occured while parsing the expression at (3:29):
    epsilon[team, gnumber] * ifelse(gnumber == 0, tau0, tau)
                             ^~~~~~
Parameters are not allowed in ifelse conditions
```

### PR DESCRIPTION
**Pull request by Dashadower**
Fixes #90

### CODE REVIEW

**Comment by bbbales2** [comment]
I added a test and am getting another error:
```
rat.types.TypeCheckError: Input Type signature ['Boolean', 'Numeric', 'Numeric'] is invalid.
Valid type signatures:

['Boolean', 'Integer', 'Integer'] -> 'Integer'
['Boolean', 'Real', 'Real'] -> 'Real'
```

I can get the error to go away by adding `real(x)` casts:
```
ifelse(gnumber == 0, real(tau0), real(tau))
```

(And then everything works)

**Comment by Dashadower** [comment]
Hmm yeah from your discord comment do you think just ditching Real and Integer for Numeric sounds better? Maybe python/numpy can handle casting and we don't have to worry about them?

**Comment by bbbales2** [comment]
> ditching Real and Integer for Numeric sounds better

Hmm, I like the sound of this in the sense that a problem goes away, but we still have to manage types and do casting and whatnot to get the underlying jax working. This doesn't sound like an issue as I'm saying it (we can just add a bunch of optional casting logic).

But if we add a bunch of casting logic... Then can't this function do [bool, Numeric, Numeric] -> Numeric?

But then we have a Numeric return type... Do you remember what we discussed on discord cause I've confused myself here.

**Comment by Dashadower** [comment]
I've defaulted to setting the type of parameters as Real. This seems straightforward and makes sense since parameters are real numbers in HMC too.

**Comment by bbbales2** [comment]
Hell yeah I was just about to ask about this lol thanks

**Comment by bbbales2** [comment]
I'll merge conflicts and get this in if tests pass

**Comment by Dashadower** [comment]
lolol yeah I also legit forgot about it

**Comment by Dashadower** [comment]
Apart from the presentations, I'm gonna work on streamlining type errors with range and stuff

**Comment by bbbales2** [comment]
Yeah I'm hitting such mental blockers on the presentation I decided I'd just rather code for a while so came back here lol.

**Comment by Dashadower** [comment]
domain stuff is still WIP, right?

**Comment by bbbales2** [comment]
Do you know what's going on here: https://github.com/bbbales2/regressions/pull/93 ? It seems like something I would have fixed but I made an issue so maybe the error was in parser?

**Comment by bbbales2** [comment]
Re: domain stuff I wanna look at cleaning that up and getting it in. I really like it.

**Comment by bbbales2** [comment]
C'mon github unit tests

**Comment by Dashadower** [comment]
> Do you know what's going on here: #93 ? It seems like something I would have fixed but I made an issue so maybe the error was in parser?

I just ran it and it raises a different error than the one set in the tests:
```
rat.exceptions.CompileError: An error occurred while compiling code at (1:22):
E                                       made' ~ normal(mu[group], 1.0);
E                                                         ^~~~~
E                                   Subscript group not found in dataframe of primary variable made
```
Looks like it should be checking if `made` exists forst?

**Review by bbbales2 — APPROVED** [review]
Hoooray!

**Pull request merged**
